AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Template creates lambda, api gateway and custom domain mapping for fetching person data.

Metadata:
  AWS::ServerlessRepo::Application:
    Name: Person
    Description: Proxy for fetching person data from the Cristin API
    Author: Unit
    SpdxLicenseId: MIT
    LicenseUrl: LICENSE
    Labels: [ '${CODEBUILD_RESOLVED_SOURCE_VERSION}', '${GIT_REPO}', '@${BUILD_TIMESTAMP}' ]

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20
    Environment:
      Variables:
        ALLOWED_ORIGIN: '*'
        CRISTIN_API_HOST: 'api.cristin.no'
        BASE_URL: 'https://api.dev.nva.aws.unit.no/person' # TODO: Dynamic from CustomDomain and CustomDomainBasePtah
  Api:
    Cors:
      AllowOrigin: "'*'"
      AllowMethods: "'OPTIONS, GET, PUT'"
      AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token, Access-Control-Allow-Origin'"

Parameters:
  CognitoAuthorizerArn:
    Type: String
    Description: Reference to Cognito UserPool for the stage
  CustomDomain:
    Type: String
    Description: Custom API to connect this lambda to
  CustomDomainBasePath:
    Type: String
    Description: Base path mapping in CustomDomain

Resources:

  ApiAccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 180

  NvaCristinPersonFunctionApi:
    Type: AWS::Serverless::Api
    Properties:
      AccessLogSetting:
        DestinationArn: !GetAtt ApiAccessLogGroup.Arn
        Format: '{ "apiId": "$context.apiId", "requestId": "$context.requestId", "requestTime": "$context.requestTime", "requestTimeEpoch": "$context.requestTimeEpoch", "httpMethod": "$context.httpMethod", "path": "$context.path", "status": "$context.status",  "error.message": "$context.error.message" }'
      StageName: Prod
      Auth:
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoAuthorizerArn
      EndpointConfiguration: Regional

  NvaCristinPersonsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      Handler: com.github.bibsysdev.nva.cristin.person.CristinPersonsHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinPersonsEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Auth:
              Authorizer: MyCognitoAuthorizer
            RestApiId: !Ref NvaCristinPersonFunctionApi
            Path: /
            Method: get
            RequestParameters:
              - method.request.querystring.language
              - method.request.querystring.name

  NvaCristinOnePersonFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.github.bibsysdev.nva.cristin.person.OneCristinPersonHandler::handleRequest
      Runtime: java11
      MemorySize: 512
      Events:
        NvaCristinOnePersonEvent:
          Type: Api
          Properties:
            Auth:
              Authorizer: MyCognitoAuthorizer
            RestApiId: !Ref NvaCristinPersonFunctionApi
            Path: /{id}
            Method: get
            RequestParameters:
              - method.request.querystring.language

  NvaCristinPersonFunctionBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      BasePath: !Ref CustomDomainBasePath
      DomainName: !Ref CustomDomain
      RestApiId: !Ref NvaCristinPersonFunctionApi
      Stage: !Ref NvaCristinPersonFunctionApi.Stage

